// Mock content shared by the sidebar and the placeholder pages until the
// back end is integrated. The shapes mirror the two real company-OS repos
// this product replaces (corma-company-os, second-brain), genericized:
// docs carry owner + verified date + source-of-truth pointers, processes have
// a lifecycle + schedule and are composed of skills reused across processes,
// connectors have a status/condition state model. Dates are preformatted
// display strings so server and client can never disagree on locale.

export type Doc = {
  slug: string;
  title: string;
  category: "company" | "wiki" | "decisions";
  owner: string;
  verifiedAt: string;
  sourceOfTruth?: string;
  excerpt: string;
  links: string[]; // slugs of related docs
};

export type Skill = {
  id: string;
  name: string;
  description: string;
};

export type Process = {
  slug: string;
  name: string;
  description: string;
  status: "draft" | "active" | "deprecated";
  kind: "deliverable" | "ops";
  owner: string;
  schedule: string | null; // null = manual / on demand
  skillIds: string[];
  connectorIds: string[];
  outputs: string[];
};

export type Connector = {
  id: string;
  name: string;
  description: string;
  category: string;
  logoUrl: string | null;
  status: "connected" | "pending" | "empty" | "disconnected";
  condition?: "degraded";
  owner: string;
};

export const docs: Doc[] = [
  {
    slug: "context-brief",
    title: "Context brief",
    category: "company",
    owner: "Alessandro",
    verifiedAt: "Jul 18, 2026",
    excerpt: "Read this first: what the company sells, to whom, and where everything lives.",
    links: ["overview", "glossary", "how-we-work"],
  },
  {
    slug: "overview",
    title: "Overview",
    category: "company",
    owner: "Alessandro",
    verifiedAt: "Jul 14, 2026",
    excerpt: "What we sell, core capabilities, ICP criteria, and the buyer personas.",
    links: ["glossary"],
  },
  {
    slug: "glossary",
    title: "Glossary",
    category: "company",
    owner: "Julien",
    verifiedAt: "Jul 10, 2026",
    sourceOfTruth: "Warehouse · metric definitions win on conflict",
    excerpt: "The definitions and IDs that make queries correct — metrics, events, and their traps.",
    links: [],
  },
  {
    slug: "people",
    title: "People",
    category: "company",
    owner: "Alessandro",
    verifiedAt: "Jul 8, 2026",
    sourceOfTruth: "Notion · Teammate directory wins on conflict",
    excerpt: "Who does what, and who owns which connector and process.",
    links: ["how-we-work"],
  },
  {
    slug: "how-we-work",
    title: "How we work",
    category: "company",
    owner: "Julien",
    verifiedAt: "Jun 30, 2026",
    excerpt: "Rituals, decision rules, and how changes ship.",
    links: ["context-brief"],
  },
  {
    slug: "voice-guide",
    title: "Voice guide",
    category: "company",
    owner: "Julien",
    verifiedAt: "Jun 27, 2026",
    excerpt: "Tone, phrasing rules, and the words we never use.",
    links: [],
  },
  {
    slug: "gtm-architecture",
    title: "GTM architecture",
    category: "wiki",
    owner: "Alessandro",
    verifiedAt: "Jun 20, 2026",
    excerpt: "The full motion from signal to campaign, as one diagram.",
    links: ["overview"],
  },
  {
    slug: "feedback-pipeline-runbook",
    title: "Feedback pipeline runbook and error handling",
    category: "wiki",
    owner: "Julien",
    verifiedAt: "Jun 12, 2026",
    excerpt: "Why the pipeline exists, how each step works, and what to do when it fails.",
    links: ["glossary"],
  },
  {
    slug: "decision-auto-merge",
    title: "Decision: auto-merge with recap",
    category: "decisions",
    owner: "Alessandro",
    verifiedAt: "Jul 20, 2026",
    excerpt: "Changes merge without review; a recap posts to Slack after the fact.",
    links: ["how-we-work"],
  },
];

export const skills: Skill[] = [
  { id: "pull-crm-records", name: "Pull CRM records", description: "Read companies, contacts, and deals from the CRM." },
  { id: "enrich-contact", name: "Enrich contact details", description: "Waterfall enrichment for emails, phones, and firmographics." },
  { id: "score-icp-fit", name: "Score ICP fit", description: "Grade an account against the ICP criteria in the glossary." },
  { id: "collect-hiring-signals", name: "Collect hiring signals", description: "Scan job postings for buying signals." },
  { id: "detect-tech-stack", name: "Detect tech stack", description: "Identify the tools a company already runs." },
  { id: "draft-outreach", name: "Draft outreach copy", description: "Write personalized sequences in the company voice." },
  { id: "sync-crm", name: "Write back to CRM", description: "Push enriched fields and notes to the CRM." },
  { id: "post-slack-digest", name: "Post Slack digest", description: "Publish a fixed-format recap to a channel." },
  { id: "extract-call-feedback", name: "Extract call feedback", description: "Pull bugs, feature asks, and sentiment from call transcripts." },
  { id: "render-report", name: "Render branded report", description: "Assemble data into the branded report template." },
  { id: "file-tickets", name: "File tickets", description: "Open tracked issues from confirmed items." },
];

export const processes: Process[] = [
  {
    slug: "lead-list-builder",
    name: "Lead list builder",
    description: "Build a scored, enriched cold list from a plain-language brief and push it to a campaign.",
    status: "active",
    kind: "deliverable",
    owner: "Alessandro",
    schedule: null,
    skillIds: [
      "enrich-contact",
      "score-icp-fit",
      "collect-hiring-signals",
      "detect-tech-stack",
      "draft-outreach",
      "sync-crm",
    ],
    connectorIds: ["hubspot", "lemlist", "slack"],
    outputs: ["CRM list", "Campaign", "Slack recap"],
  },
  {
    slug: "weekly-feedback-report",
    name: "Weekly feedback report",
    description: "Turn the week's call transcripts into a report, tickets, and a Slack recap.",
    status: "active",
    kind: "deliverable",
    owner: "Julien",
    schedule: "Mon 09:00",
    skillIds: ["extract-call-feedback", "render-report", "post-slack-digest", "file-tickets"],
    connectorIds: ["notion", "slack"],
    outputs: ["Report page", "Tickets", "Slack recap"],
  },
  {
    slug: "competitor-watch",
    name: "Competitor watch",
    description: "Monitor competitor accounts for engagement signals and start outreach.",
    status: "active",
    kind: "deliverable",
    owner: "Alessandro",
    schedule: "Mon + Thu 07:00",
    skillIds: ["collect-hiring-signals", "detect-tech-stack", "draft-outreach", "post-slack-digest"],
    connectorIds: ["hubspot", "lemlist", "slack"],
    outputs: ["Campaign", "Slack recap"],
  },
  {
    slug: "churn-alerts",
    name: "Churn alerts",
    description: "Watch product usage for drop-off patterns and alert the account owner.",
    status: "active",
    kind: "ops",
    owner: "Julien",
    schedule: "Daily 08:00",
    skillIds: ["pull-crm-records", "post-slack-digest"],
    connectorIds: ["zohoanalytics", "hubspot", "slack"],
    outputs: ["Slack alert"],
  },
  {
    slug: "workspace-health-check",
    name: "Workspace health check",
    description: "Probe every connector, flag stale docs, and report drift before it bites.",
    status: "active",
    kind: "ops",
    owner: "Alessandro",
    schedule: "Daily 08:00",
    skillIds: ["post-slack-digest"],
    connectorIds: ["notion", "slack"],
    outputs: ["Slack heartbeat"],
  },
  {
    slug: "founder-content-drafts",
    name: "Founder content drafts",
    description: "Draft daily social posts in the founder's voice for review by emoji.",
    status: "draft",
    kind: "deliverable",
    owner: "Julien",
    schedule: null,
    skillIds: ["draft-outreach", "post-slack-digest"],
    connectorIds: ["slack"],
    outputs: ["Slack drafts"],
  },
  {
    slug: "invoice-sync",
    name: "Invoice sync",
    description: "Reconcile invoices between billing and accounting, flag mismatches.",
    status: "deprecated",
    kind: "ops",
    owner: "Alessandro",
    schedule: null,
    skillIds: ["pull-crm-records", "sync-crm"],
    connectorIds: ["hubspot"],
    outputs: ["Ledger updates"],
  },
];

export const connectors: Connector[] = [
  {
    id: "serper",
    name: "Serper",
    description: "recherche web",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/serper.dev?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Alessandro",
  },
  {
    id: "hunter",
    name: "Hunter.io",
    description: "emails",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/hunter.io?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "sirene",
    name: "INSEE SIRENE",
    description: "données entreprise FR",
    category: "Data FR",
    logoUrl: "https://img.logo.dev/insee.fr?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "disconnected",
    owner: "Alessandro",
  },
  {
    id: "droit",
    name: "Info légale FR",
    description: "jurisprudence, codes consolidés, conventions collectives (open data DILA/Légifrance)",
    category: "Data FR",
    logoUrl: "https://img.logo.dev/legifrance.gouv.fr?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "pending",
    owner: "Julien",
  },
  {
    id: "attio",
    name: "Attio",
    description: "CRM",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/attio.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "empty",
    owner: "Alessandro",
  },
  {
    id: "lemlist",
    name: "Lemlist",
    description: "cold outreach",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/lemlist.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "kaspr",
    name: "Kaspr",
    description: "enrichissement",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/kaspr.io?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Alessandro",
  },
  {
    id: "pennylane",
    name: "Pennylane",
    description: "compta",
    category: "Finance",
    logoUrl: "https://img.logo.dev/pennylane.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "slack",
    name: "Slack",
    description: "messagerie Slack (bot token xoxb- et/ou user token xoxp-)",
    category: "Comms",
    logoUrl: "https://img.logo.dev/slack.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "disconnected",
    owner: "Alessandro",
  },
  {
    id: "fullenrich",
    name: "FullEnrich",
    description: "enrichissement waterfall",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/fullenrich.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "pending",
    owner: "Julien",
  },
  {
    id: "folk",
    name: "Folk",
    description: "CRM",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/folk.app?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    condition: "degraded",
    owner: "Alessandro",
  },
  {
    id: "unipile",
    name: "Messagerie hébergée (Unipile)",
    description: "LinkedIn + WhatsApp + Telegram + Instagram + Messenger + X/Twitter hébergés (recherche/scrape/messagerie)",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/unipile.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "topograph",
    name: "Topograph",
    description: "KYB — données & documents entreprise (registres européens)",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/topograph.co?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Alessandro",
  },
  {
    id: "resend",
    name: "Resend",
    description: "envoi d'email transactionnel (clé de l'org)",
    category: "Autres",
    logoUrl: null,
    status: "connected",
    owner: "Julien",
  },
  {
    id: "scaleway",
    name: "Scaleway TEM (email)",
    description: "envoi d'email transactionnel via ton compte Scaleway TEM (domaine vérifié chez Scaleway)",
    category: "Autres",
    logoUrl: null,
    status: "disconnected",
    owner: "Alessandro",
  },
  {
    id: "silae",
    name: "Silae",
    description: "paie FR (lecture) — API Silae Paie v1",
    category: "Finance",
    logoUrl: "https://img.logo.dev/silae.fr?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "pending",
    owner: "Julien",
  },
  {
    id: "gocardless",
    name: "GoCardless",
    description: "prélèvements SEPA (lecture)",
    category: "Finance",
    logoUrl: "https://img.logo.dev/gocardless.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "empty",
    owner: "Alessandro",
  },
  {
    id: "folkmcp",
    name: "Folk (MCP)",
    description: "CRM Folk via son MCP officiel (fédéré, OAuth per-user)",
    category: "Autres",
    logoUrl: null,
    status: "connected",
    owner: "Julien",
  },
  {
    id: "planity",
    name: "Planity",
    description: "agenda + caisse Planity (RDV, clients, CA, stats) — MCP fédéré",
    category: "Métier",
    logoUrl: "https://img.logo.dev/planity.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Alessandro",
  },
  {
    id: "aiark",
    name: "AI Ark",
    description: "people & company search via LinkedIn",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/ai-ark.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "cognism",
    name: "Cognism",
    description: "B2B contact & company search, reveal, and identity enrichment",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/cognism.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "disconnected",
    owner: "Alessandro",
  },
  {
    id: "crunchbase",
    name: "Crunchbase",
    description: "fiches société/personne (session Browserbase)",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/crunchbase.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "pending",
    owner: "Julien",
  },
  {
    id: "brevoauto",
    name: "Brevo (automation)",
    description: "automations marketing (session Browserbase)",
    category: "Automatisation",
    logoUrl: "https://img.logo.dev/brevo.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "empty",
    owner: "Alessandro",
  },
  {
    id: "pennylaneged",
    name: "Pennylane GED",
    description: "bac documentaire Pennylane (session Browserbase)",
    category: "Finance",
    logoUrl: "https://img.logo.dev/pennylane.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "google",
    name: "Google",
    description: "Gmail + Tasks + Calendar + Sheets + Drive + Chat (OAuth)",
    category: "Comms",
    logoUrl: "https://img.logo.dev/google.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Alessandro",
  },
  {
    id: "culture",
    name: "Culture (open data)",
    description: "entreprises du spectacle vivant — open data Ministère de la Culture",
    category: "Data FR",
    logoUrl: "https://img.logo.dev/culture.gouv.fr?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "reddit",
    name: "Reddit",
    description: "recherche & lecture de posts/subreddits (API publique)",
    category: "Web",
    logoUrl: "https://img.logo.dev/reddit.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "disconnected",
    owner: "Alessandro",
  },
  {
    id: "gr",
    name: "Data GR",
    description: "entreprises Grèce — registre GEMI + VIES (open data)",
    category: "Data GR",
    logoUrl: null,
    status: "pending",
    owner: "Julien",
  },
  {
    id: "foncier",
    name: "Foncier",
    description: "géocodage, cadastre, bâti, risques/ICPE, solaire, immobilier (open data)",
    category: "Data FR",
    logoUrl: "https://img.logo.dev/data.gouv.fr?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "empty",
    owner: "Alessandro",
  },
  {
    id: "urba",
    name: "Urbanisme",
    description: "zonage PLU/GPU, risques, QPV, EPFIF, socio-démo commune (open data)",
    category: "Autres",
    logoUrl: "https://img.logo.dev/geoportail-urbanisme.gouv.fr?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "sante",
    name: "Santé",
    description: "établissements FINESS + évaluations ESSMS HAS (open data)",
    category: "Data FR",
    logoUrl: "https://img.logo.dev/has-sante.fr?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Alessandro",
  },
  {
    id: "osm",
    name: "OpenStreetMap",
    description: "points d'intérêt OSM par tag sur une zone (parkings, équipements, commerces) — recensement exhaustif via Overpass (open data)",
    category: "Autres",
    logoUrl: null,
    status: "connected",
    owner: "Julien",
  },
  {
    id: "frenchtech",
    name: "French Tech",
    description: "annuaire écosystème d'une capitale French Tech (startups/structures/prestataires) + événements, appels à projet, financements + French Tech Central (open data, défaut Aix-Marseille)",
    category: "Data FR",
    logoUrl: "https://img.logo.dev/lafrenchtech.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "disconnected",
    owner: "Alessandro",
  },
  {
    id: "infosec",
    name: "Infosec",
    description: "empreinte numérique d'un domaine : whois/RDAP, DNS, posture e-mail (SPF/DMARC), sous-domaines (CT), TLS, headers de sécurité (recon passif)",
    category: "Infosec",
    logoUrl: null,
    status: "pending",
    owner: "Julien",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "CRM (contacts, companies, deals, tickets, notes)",
    category: "Prospection",
    logoUrl: null,
    status: "empty",
    owner: "Alessandro",
  },
  {
    id: "brevo",
    name: "Brevo",
    description: "emailing & CRM (contacts, listes, transactionnel, campagnes, deals)",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/brevo.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "apollo",
    name: "Apollo.io",
    description: "prospection B2B (organizations, people, job postings)",
    category: "Prospection",
    logoUrl: null,
    status: "connected",
    owner: "Alessandro",
  },
  {
    id: "zerobounce",
    name: "ZeroBounce",
    description: "vérification de délivrabilité email",
    category: "Prospection",
    logoUrl: null,
    status: "connected",
    owner: "Julien",
  },
  {
    id: "hithorizons",
    name: "HitHorizons",
    description: "données entreprise européennes (recherche + détails)",
    category: "Prospection",
    logoUrl: null,
    status: "disconnected",
    owner: "Alessandro",
  },
  {
    id: "phantombuster",
    name: "Phantombuster",
    description: "agents d'automatisation (launch + résultats)",
    category: "Prospection",
    logoUrl: null,
    status: "pending",
    owner: "Julien",
  },
  {
    id: "notion",
    name: "Notion",
    description: "pages, bases de données, blocs (lecture + écriture)",
    category: "Knowledge",
    logoUrl: null,
    status: "empty",
    owner: "Alessandro",
  },
  {
    id: "figma",
    name: "Figma",
    description: "fichiers, export d'images, commentaires, FigJam",
    category: "Design",
    logoUrl: null,
    status: "connected",
    owner: "Julien",
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "Management API (projets, config auth, logs)",
    category: "Dev",
    logoUrl: null,
    status: "connected",
    owner: "Alessandro",
  },
  {
    id: "zoho",
    name: "Zoho CRM",
    description: "CRM Zoho (CRUD modules, notes)",
    category: "Prospection",
    logoUrl: null,
    status: "connected",
    condition: "degraded",
    owner: "Julien",
  },
  {
    id: "zohodesk",
    name: "Zoho Desk",
    description: "support Zoho Desk (tickets, threads, contacts)",
    category: "Comms",
    logoUrl: null,
    status: "disconnected",
    owner: "Alessandro",
  },
  {
    id: "zohoanalytics",
    name: "Zoho Analytics",
    description: "Zoho Analytics (workspaces, vues, export, requêtes SQL)",
    category: "Knowledge",
    logoUrl: null,
    status: "pending",
    owner: "Julien",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "CRM Salesforce (Contacts, Accounts/companies, Leads, Opportunities, notes)",
    category: "Prospection",
    logoUrl: null,
    status: "empty",
    owner: "Alessandro",
  },
  {
    id: "greenhouse",
    name: "Greenhouse",
    description: "ATS — candidats, jobs, candidatures, notes (Harvest API)",
    category: "Recrutement",
    logoUrl: "https://img.logo.dev/greenhouse.io?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "lever",
    name: "Lever",
    description: "ATS — opportunities (candidats), postings, stages, notes",
    category: "Recrutement",
    logoUrl: "https://img.logo.dev/lever.co?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Alessandro",
  },
  {
    id: "ashby",
    name: "Ashby",
    description: "ATS — candidates, jobs, applications, notes",
    category: "Recrutement",
    logoUrl: "https://img.logo.dev/ashbyhq.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "teamtailor",
    name: "Teamtailor",
    description: "ATS — candidats, jobs, candidatures (JSON:API)",
    category: "Recrutement",
    logoUrl: "https://img.logo.dev/teamtailor.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "disconnected",
    owner: "Alessandro",
  },
  {
    id: "recruitee",
    name: "Recruitee",
    description: "ATS — candidats, offers (postes), notes",
    category: "Recrutement",
    logoUrl: "https://img.logo.dev/recruitee.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "pending",
    owner: "Julien",
  },
  {
    id: "serpapi",
    name: "SerpApi",
    description: "recherche multi-moteurs (Google verticals, Bing, YouTube, Walmart, Amazon, jobs…)",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/serpapi.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "empty",
    owner: "Alessandro",
  },
  {
    id: "searchapi",
    name: "SearchApi",
    description: "recherche multi-moteurs (Google verticals, YouTube, Bing, jobs, news, maps, scholar…)",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/searchapi.io?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "brightdata",
    name: "Bright Data",
    description: "scraping & SERP via proxy (coquille vide — à implémenter)",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/brightdata.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    condition: "degraded",
    owner: "Alessandro",
  },
  {
    id: "cloro",
    name: "Cloro",
    description: "veille AI-search (ChatGPT, Gemini, Perplexity…) + SERP Google JSON",
    category: "Prospection",
    logoUrl: "https://img.logo.dev/cloro.dev?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "connected",
    owner: "Julien",
  },
  {
    id: "n8n",
    name: "n8n",
    description: "automatisation de workflows — workflows + exécutions (API publique)",
    category: "Automatisation",
    logoUrl: "https://img.logo.dev/n8n.io?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "disconnected",
    owner: "Alessandro",
  },
  {
    id: "make",
    name: "Make",
    description: "automatisation de workflows — scénarios, exécution, logs (API v2)",
    category: "Automatisation",
    logoUrl: "https://img.logo.dev/make.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "pending",
    owner: "Julien",
  },
  {
    id: "zapier",
    name: "Zapier",
    description: "automatisation — actions exposées (AI Actions) + exécution",
    category: "Automatisation",
    logoUrl: "https://img.logo.dev/zapier.com?token=pk_Hvj44EaUSjmsX5fB3VGBXA&size=256&format=png&retina=true",
    status: "empty",
    owner: "Alessandro",
  },
  {
    id: "http",
    name: "HTTP",
    description: "connecte n'importe quelle API HTTP à oto : renseigne l'URL de base, le mode d'auth (bearer / clé en header ou query / basic / oauth2) et le secret correspondant. oto stocke le secret (coffre chiffré) et tape l'API directement, en lecture seule (GET).",
    category: "Autres",
    logoUrl: null,
    status: "connected",
    owner: "Julien",
  },
];

export const getDoc = (slug: string) => docs.find((d) => d.slug === slug);
export const getProcess = (slug: string) => processes.find((p) => p.slug === slug);
export const getSkill = (id: string) => skills.find((s) => s.id === id);
export const getConnector = (id: string) => connectors.find((c) => c.id === id);
